services:
  xrpic:
    # build:
    #   context: .
    images: ghcr.io/xrgzs/xrpic:latest
    container_name: xrpic
    ports:
      - "36677:36677"
    # volumes:
      # - ./config.json:/app/config.json
      # - ./uploads:/app/uploads
    # environment:
      # - APP_AUTH_ENABLED=true
      # - APP_AUTH_SECRET_KEY=your_secret_key_here
      # - APP_SERVER_HOST=0.0.0.0
      # - APP_SERVER_PORT=36677
      # - APP_STORAGE_BASE_URL=http://img.example.com
      # - APP_STORAGE_UPLOAD_DIR=/app/uploads
      # - APP_STORAGE_MAX_FILE_SIZE=10485760
